import * as T from 'three';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {UnrealBloomPass} from 'three/addons/postprocessing/UnrealBloomPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
import {SPB,SPEED,depth,zones,zoneAt} from './course.js';
const box=new T.BoxGeometry(1,1,1),orb=new T.IcosahedronGeometry(.38,1);
function mesh(g,m,x,y,z,sx=1,sy=1,sz=1){const o=new T.Mesh(g,m);o.position.set(x,y,z);o.scale.set(sx,sy,sz);return o;}
export class World{
 constructor(canvas){this.renderer=new T.WebGLRenderer({canvas,antialias:false,powerPreference:'high-performance'});this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.1;
 this.scene=new T.Scene();this.scene.fog=new T.FogExp2(0x060718,.008);this.camera=new T.PerspectiveCamera(62,innerWidth/innerHeight,.1,450);this.distance=8.3;this.reduced=true;this.scene.add(new T.HemisphereLight(0xc0d9ff,0x342448,2.3));const key=new T.DirectionalLight(0xf1e6ff,3.5);key.position.set(-3,7,4);this.scene.add(key);this.rim=new T.PointLight(0x12ddff,70,22);this.rim.position.set(0,4,3);this.scene.add(this.rim);
 this.metal=new T.MeshStandardMaterial({color:0x252b40,metalness:.75,roughness:.33});this.dark=new T.MeshStandardMaterial({color:0x080c22,metalness:.7,roughness:.28});this.neon=new T.MeshStandardMaterial({color:0x32d9ff,emissive:0x00bfff,emissiveIntensity:2,metalness:.3,roughness:.3});this.accent=new T.MeshStandardMaterial({color:0x884fff,emissive:0x7933ff,emissiveIntensity:1.6});this.red=new T.MeshStandardMaterial({color:0xff3979,emissive:0xb90832,emissiveIntensity:1.5,metalness:.35,roughness:.3});this.gold=new T.MeshStandardMaterial({color:0xffd475,emissive:0xffa629,emissiveIntensity:1.3,metalness:.6,roughness:.2});
 this.arch=[];for(let i=0;i<20;i++){const g=new T.Group();g.userData.i=i;for(const side of [-1,1]){g.add(mesh(box,this.metal,side*5.1,3.1,0,.7,6.4,1.2));g.add(mesh(box,this.neon,side*4.7,3.0,.03,.08,5.7,1.28));const slant=mesh(box,this.metal,side*3.9,6.5,0,.65,3.6,1.2);slant.rotation.z=side*.7;g.add(slant);const neon=mesh(box,this.accent,side*3.6,6.5,.05,.07,3.5,1.24);neon.rotation.z=side*.7;g.add(neon);g.add(mesh(box,this.dark,side*5.2,1.2,-3,1.1,2.4,5.8));g.add(mesh(box,this.accent,side*4.62,1.9,-3,.06,.16,4.7));for(let k=0;k<4;k++)g.add(mesh(box,this.neon,side*4.61,.6+k*.25,-3,.05,.09,1.3+k*.5));}
 g.add(mesh(box,this.metal,0,7.8,0,5.8,.6,1.3));g.add(mesh(box,this.neon,0,7.45,0,3.4,.07,.8));g.add(mesh(box,this.dark,0,-.18,-3,10,.3,8));for(const x of [-3.7,-1.2,1.2,3.7])g.add(mesh(box,x===-3.7||x===3.7?this.neon:this.accent,x,.002,-3,.04,.025,8));g.add(mesh(box,this.metal,0,-.01,0,8,.035,.15));this.scene.add(g);this.arch.push(g);}
 // Deep-space sky: continuous layered procedural nebula, stars, dust and a galactic plane.
 this.sky=new T.Mesh(new T.SphereGeometry(390,32,16),new T.ShaderMaterial({side:T.BackSide,depthWrite:false,uniforms:{uTime:{value:0}},vertexShader:`varying vec3 v;void main(){v=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`precision highp float;varying vec3 v;uniform float uTime;float hash(vec3 p){return fract(sin(dot(p,vec3(127.1,311.7,74.7)))*43758.5453);}float noise(vec3 p){vec3 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(mix(hash(i),hash(i+vec3(1,0,0)),f.x),mix(hash(i+vec3(0,1,0)),hash(i+vec3(1,1,0)),f.x),f.y),mix(mix(hash(i+vec3(0,0,1)),hash(i+vec3(1,0,1)),f.x),mix(hash(i+vec3(0,1,1)),hash(i+vec3(1,1,1)),f.x),f.y),f.z);}float fbm(vec3 p){float a=.5,s=0.;for(int i=0;i<5;i++){s+=a*noise(p);p=p*2.03+1.7;a*=.5;}return s;}void main(){vec3 d=normalize(v);float n=fbm(d*5.+vec3(uTime*.003,0,0));float ribbon=exp(-abs(d.y+d.x*.45+.04)*7.);float cloud=pow(max(0.,n-.22),2.)*ribbon;vec3 c=vec3(.006,.008,.028)+cloud*vec3(.36,.12,.65)+pow(max(0.,fbm(d*9.)-.4),2.)*vec3(.05,.6,.9);vec3 grid=d*300.;float star=pow(hash(floor(grid)),180.)*pow(max(0.,1.-length(fract(grid)-.5)),12.)*110.;gl_FragColor=vec4(c+star*vec3(.6,.75,1.),1.);}`}));this.scene.add(this.sky);
 const planet=new T.Mesh(new T.SphereGeometry(17,48,32),new T.MeshStandardMaterial({color:0x544a92,roughness:.85,metalness:.2}));planet.position.set(36,26,-130);this.scene.add(planet);const halo=mesh(new T.TorusGeometry(23,.4,8,96),this.accent,36,26,-130);halo.rotation.x=1.1;halo.rotation.y=.25;this.scene.add(halo);
 this.portal=new T.Group();this.portal.position.set(0,3.2,-155);for(let i=0;i<4;i++){const r=mesh(new T.TorusGeometry(6+i*1.5,.2,8,64),i%2?this.neon:this.accent,0,0,-i*2);this.portal.add(r);}this.scene.add(this.portal);
 this.lasers=[];for(let i=0;i<8;i++){const g=new T.Group();g.position.set(i%2?5:-5,5,-i*18);const light=mesh(new T.ConeGeometry(.65,16,8,1,true),new T.MeshBasicMaterial({color:i%2?0x962fff:0x13dfff,transparent:true,opacity:.09,blending:T.AdditiveBlending,depthWrite:false,side:T.DoubleSide}),0,-8,0);g.add(light);this.scene.add(g);this.lasers.push(g);}
 this.objects=new Map();this.particles=[];this.composer=new EffectComposer(this.renderer);this.composer.addPass(new RenderPass(this.scene,this.camera));this.bloom=new UnrealBloomPass(new T.Vector2(innerWidth/2,innerHeight/2),.45,.45,1.05);this.composer.addPass(this.bloom);this.composer.addPass(new OutputPass());this.quality('auto');this.resize();addEventListener('resize',()=>this.resize());
 }
 quality(q){this.preset=q;this.dpr=q==='low'?1:q==='ultra'?Math.min(devicePixelRatio,2):Math.min(devicePixelRatio,1.4);this.bloom.enabled=q!=='low';this.renderer.setPixelRatio(this.dpr);this.composer.setPixelRatio(this.dpr);this.resize();}
 resize(){this.renderer.setSize(innerWidth,innerHeight);this.composer.setSize(innerWidth,innerHeight);this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();}
 reset(){for(const o of this.objects.values())this.scene.remove(o);this.objects.clear();for(const p of this.particles)this.scene.remove(p);this.particles=[];}
 burst(x,hit=false){for(let i=0;i<16;i++){const p=mesh(orb,hit?this.red:this.gold,x,1.3,0,.15,.15,.15);p.userData={life:1,v:new T.Vector3(Math.sin(i*2.4)*3,1+Math.cos(i)*2,Math.cos(i*2.4)*3)};this.scene.add(p);this.particles.push(p);}}
 update(beat,dt,run,active){const z=zoneAt(beat),zone=zones[z];this.neon.color.lerp(new T.Color(zone.color),dt);this.neon.emissive.lerp(new T.Color(zone.color),dt);this.accent.emissive.lerp(new T.Color(zone.accent),dt);const pulse=Math.exp(-(beat%1)*8);this.neon.emissiveIntensity=1.4+pulse*(this.reduced?.2:.7);this.rim.intensity=55+pulse*15;this.sky.material.uniforms.uTime.value=beat*SPB;this.portal.rotation.z=Math.sin(beat*.04)*.18;
 const travel=beat*SPB*SPEED;for(const g of this.arch){g.position.z=12-((g.userData.i*8-travel)%160+160)%160;g.scale.y=T.MathUtils.damp(g.scale.y,z===1?1.45:1,1,dt);g.visible=z!==2||g.userData.i%3===0;}
 this.lasers.forEach((g,i)=>{g.rotation.z=Math.sin(beat*.22+i)*.55;g.rotation.x=Math.cos(beat*.14+i)*.2;});
 for(const e of run?.events||[]){const zz=depth(e.beat,beat);if(zz>8||e.passed){const o=this.objects.get(e.id);if(o){this.scene.remove(o);this.objects.delete(e.id);}continue;}if(zz<-100)continue;let o=this.objects.get(e.id);if(!o){o=new T.Group();const pickup=e.kind==='orb'||e.kind==='shield';if(pickup){o.add(mesh(orb,e.kind==='shield'?this.neon:this.gold,0,1.25,0));o.add(mesh(new T.TorusGeometry(.58,.045,6,24),e.kind==='shield'?this.neon:this.gold,0,1.25,0));}else{const h=e.kind==='laser'?2.2:1.7;o.add(mesh(box,this.dark,0,h/2,0,1.75,h,.6));o.add(mesh(box,this.red,0,h,0,1.85,.12,.7));for(const s of [-1,1])o.add(mesh(box,this.red,s*.86,h/2,0,.1,h,.7));if(e.kind==='shard')o.rotation.z=.12;}this.scene.add(o);this.objects.set(e.id,o);}o.position.set(e.x,0,zz);if(e.kind==='orb'||e.kind==='shield')o.rotation.y=beat*1.8;
 }
 for(let i=this.particles.length-1;i>=0;i--){const p=this.particles[i];p.userData.life-=dt;p.position.addScaledVector(p.userData.v,dt);p.scale.setScalar(Math.max(0,p.userData.life)*.2);if(p.userData.life<=0){this.scene.remove(p);this.particles.splice(i,1);}}
 const x=run?.x||0;this.camera.position.set(x*.22,3.8,this.distance);this.camera.lookAt(x*.08,2,-15);this.camera.fov=T.MathUtils.damp(this.camera.fov,active&&z===3?67:62,2,dt);this.camera.updateProjectionMatrix();
 }
 render(){this.composer.render();}
}
