import {SPB,FIXED_STEP,PLAYER_RADIUS,MAX_SPEED,validateChart,createRun,setTarget,advanceRun,makeLasers,makePickups,activeSection,accuracy} from "./engine.js";

const $=id=>document.getElementById(id),tg=window.Telegram?.WebApp;
if(tg){try{tg.ready();tg.expand();if(tg.isVersionAtLeast?.("7.7"))tg.disableVerticalSwipes?.();}catch{}}
const root=$("app"),canvas=$("game"),ctx=canvas.getContext("2d",{alpha:false});
const screens=[...document.querySelectorAll(".screen")],hud=$("hud"),hint=$("touch-hint"),toast=$("toast");
const state={screen:"menu",chart:null,buffer:null,run:null,difficulty:"normal",audio:null,source:null,musicGain:null,sfxGain:null,startAt:0,offsetBeat:0,counting:false,lastFrame:0,accumulator:0,toastTimer:0,pointerId:null,settings:{music:.72,sfx:.45,offset:0,reduced:window.matchMedia?.("(prefers-reduced-motion: reduce)").matches||false},best:{normal:0,hard:0},width:innerWidth,height:innerHeight,scale:1,worldHeight:600,playerY:450,ticks:new Set()};
function clamp(n,a,b,f){return Number.isFinite(n)?Math.max(a,Math.min(b,n)):f;}
try{const p=JSON.parse(localStorage.getItem("makar-zhenya-v1")||"{}");state.best={normal:Math.max(0,Number(p.best?.normal)||0),hard:Math.max(0,Number(p.best?.hard)||0)};Object.assign(state.settings,p.settings||{});}catch{}
state.settings.music=clamp(Number(state.settings.music),0,1,.72);state.settings.sfx=clamp(Number(state.settings.sfx),0,1,.45);state.settings.offset=clamp(Number(state.settings.offset),-150,150,0);state.settings.reduced=Boolean(state.settings.reduced);
document.title="МАКАР + ЖЕНЯ";
function persist(){try{localStorage.setItem("makar-zhenya-v1",JSON.stringify({best:state.best,settings:state.settings}));}catch{toastMessage("Рекорд сохранён до закрытия страницы.");}}
function showScreen(id){screens.forEach(s=>s.classList.toggle("active",s.id===id));state.screen=id==="none"?"playing":id.replace("-screen","");hud.classList.toggle("visible",["playing","pause"].includes(state.screen));hint.classList.toggle("visible",state.screen==="playing");}
function toastMessage(message){toast.textContent=message;toast.classList.add("show");clearTimeout(state.toastTimer);state.toastTimer=setTimeout(()=>toast.classList.remove("show"),1900);}
function fit(){state.width=innerWidth;state.height=tg?.viewportStableHeight||innerHeight;state.scale=Math.min(state.width/360,state.height/460);state.worldHeight=state.height/state.scale;state.playerY=state.worldHeight*.75;canvas.width=Math.round(state.width*Math.min(devicePixelRatio||1,2));canvas.height=Math.round(state.height*Math.min(devicePixelRatio||1,2));canvas.style.height=state.height+"px";root.style.height=state.height+"px";state.pointerId=null;ctx.setTransform(canvas.width/state.width,0,0,canvas.height/state.height,0,0);if(state.run){state.run.playerY=state.playerY;state.run.worldHeight=state.worldHeight;state.run.x=clamp(state.run.x,PLAYER_RADIUS,360-PLAYER_RADIUS,180);state.run.targetX=clamp(state.run.targetX,16,344,180);}}
fit();addEventListener("resize",fit);tg?.onEvent?.("viewportChanged",fit);
function safeArea(){if(!tg)return;const a=tg.contentSafeAreaInset||{},b=tg.safeAreaInset||{};for(const side of ["top","right","bottom","left"]){const n=Math.max(Number(a[side])||0,Number(b[side])||0);const key="--safe-"+({top:"t",right:"r",bottom:"b",left:"l"})[side];if(n)root.style.setProperty(key,n+"px");else root.style.removeProperty(key);}}
try{tg?.setHeaderColor?.("#070a16");tg?.setBackgroundColor?.("#070a16");}catch{}
safeArea();tg?.onEvent?.("safeAreaChanged",safeArea);tg?.onEvent?.("contentSafeAreaChanged",safeArea);
function applySettings(){ root.classList.toggle("reduced-effects",state.settings.reduced);$("music-volume").value=state.settings.music;$("sfx-volume").value=state.settings.sfx;$("offset").value=state.settings.offset;$("offset-value").value=Math.round(state.settings.offset)+" мс";$("reduced-motion").checked=state.settings.reduced;if(state.musicGain)state.musicGain.gain.setTargetAtTime(state.settings.music,state.audio.currentTime,.03);}
function ensureAudio(){if(state.audio)return state.audio;const C=window.AudioContext||window.webkitAudioContext;if(!C)throw new Error("В этом браузере нет Web Audio API.");state.audio=new C();state.musicGain=state.audio.createGain();state.sfxGain=state.audio.createGain();state.musicGain.gain.value=state.settings.music;state.sfxGain.gain.value=state.settings.sfx;const comp=state.audio.createDynamicsCompressor();comp.threshold.value=-12;comp.knee.value=14;comp.ratio.value=3;comp.attack.value=.004;comp.release.value=.18;state.musicGain.connect(comp);state.sfxGain.connect(comp);comp.connect(state.audio.destination);const size=Math.ceil(state.audio.sampleRate*.18),noise=state.audio.createBuffer(1,size,state.audio.sampleRate),data=noise.getChannelData(0);for(let i=0;i<size;i++)data[i]=Math.random()*2-1;state.noiseBuffer=noise;state.audio.addEventListener("statechange",()=>{if(state.audio.state!=="running")pauseRun(true);});return state.audio;}
async function loadTrack(){if(state.chart&&state.buffer)return;$("loading-progress").style.width="12%";$("loading-message").textContent="ЧИТАЕМ РИТМИЧЕСКУЮ КАРТУ…";const res=await fetch("./assets/charts/rave-140.json",{cache:"no-cache"});if(!res.ok)throw new Error("Не удалось загрузить музыкальную карту.");const chart=validateChart(await res.json());$("loading-progress").style.width="32%";const resAudio=await fetch("./assets/audio/neon-rush-140.mp3");if(!resAudio.ok)throw new Error("Не удалось загрузить техно-трек.");$("loading-message").textContent="ЗАГРУЖАЕМ ORIGINAL TECHNO…";const raw=await resAudio.arrayBuffer();if(chart.audioSha256&&crypto?.subtle){const hash=await crypto.subtle.digest("SHA-256",raw.slice(0));const hex=[...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,"0")).join("");if(hex!==chart.audioSha256)throw new Error("Версия музыкального файла не совпадает с картой.");}$("loading-progress").style.width="70%";state.buffer=await state.audio.decodeAudioData(raw.slice(0));state.chart=chart;$("loading-progress").style.width="100%";}
function scheduleTick(time,strong){const a=state.audio,o=a.createOscillator(),g=a.createGain();o.type=strong?"triangle":"sine";o.frequency.setValueAtTime(strong?880:620,time);o.frequency.exponentialRampToValueAtTime(180,time+.055);g.gain.setValueAtTime(.0001,time);g.gain.exponentialRampToValueAtTime(strong?.16:.09,time+.003);g.gain.exponentialRampToValueAtTime(.0001,time+.07);o.connect(g);g.connect(state.sfxGain);state.ticks.add(o);o.onended=()=>state.ticks.delete(o);o.start(time);o.stop(time+.08);}
function playSfx(kind){if(!state.audio||!state.sfxGain||!kind)return;const now=state.audio.currentTime,vol=state.settings.sfx;if(vol<=.001)return;const g=state.audio.createGain();g.connect(state.sfxGain);if(kind==="hit"||kind==="shield"){const n=state.audio.createBufferSource(),f=state.audio.createBiquadFilter();n.buffer=state.noiseBuffer;f.type="lowpass";f.frequency.value=kind==="hit"?900:1800;g.gain.setValueAtTime((kind==="hit"?.22:.11)*vol,now);g.gain.exponentialRampToValueAtTime(.0001,now+.14);n.connect(f);f.connect(g);n.start(now);n.stop(now+.15);return;}const o=state.audio.createOscillator(),freq=kind==="perfect"?940:kind==="good"?650:kind==="risk"?1160:kind==="flow"?520:kind==="pickup"?780:350;o.type="triangle";o.frequency.setValueAtTime(freq,now);o.frequency.exponentialRampToValueAtTime(Math.max(90,freq*.57),now+.11);const peak=(kind==="risk"?.085:kind==="flow"?.095:kind==="pickup"?.07:.045)*vol;g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(peak,now+.004);g.gain.exponentialRampToValueAtTime(.0001,now+.12);o.connect(g);o.start(now);o.stop(now+.13);}
function startCountIn(offsetBeat){if(!state.audio||!state.buffer||!state.chart)return;stopSource();state.run=state.run||createRun(state.chart,state.difficulty);state.run.playerY=state.playerY;state.run.worldHeight=state.worldHeight;state.offsetBeat=offsetBeat;state.counting=true;state.startAt=state.audio.currentTime+4*SPB;for(let i=0;i<4;i++)scheduleTick(state.audio.currentTime+i*SPB,i===0);const src=state.audio.createBufferSource();src.buffer=state.buffer;src.connect(state.musicGain);const offsetSeconds=Math.max(0,offsetBeat*SPB+state.chart.firstBeatSeconds);src.start(state.startAt,offsetSeconds);state.source=src;src.onended=()=>{if(state.screen==="playing"&&state.run&&!state.run.ended&&!state.run.finished)finishRun(true);};state.accumulator=0;state.lastFrame=performance.now();$("loading-message").textContent="4 УДАРА ДО СТАРТА";$("loading-progress").style.width="100%";state.countdownStart=state.audio.currentTime;showScreen("loading-screen");state.screen="countdown";}
async function begin(){if(["loading","playing","countdown"].includes(state.screen))return;state.difficulty=document.querySelector(".difficulty.selected")?.dataset.difficulty||state.difficulty;state.interrupted=false;keys.clear();showScreen("loading-screen");$("loading-message").textContent="ПОДКЛЮЧАЕМ ЗВУК…";$("loading-progress").style.width="4%";try{ensureAudio();await state.audio.resume();await loadTrack();if(document.hidden||state.interrupted){showScreen("menu-screen");toastMessage("Загрузка завершена. Нажми кнопку игры, чтобы начать.");return;}state.run=createRun(state.chart,state.difficulty);state.run.playerY=state.playerY;state.run.worldHeight=state.worldHeight;state.pointerId=null;startCountIn(0);}catch(e){showScreen("menu-screen");toastMessage(e.message||"Не удалось запустить игру.");}}
function stopSource(){for(const tick of state.ticks){try{tick.stop();}catch{}}state.ticks.clear();if(state.source){try{state.source.onended=null;state.source.stop();}catch{}state.source=null;}}
function audibleBeat(){if(!state.audio||!state.startAt)return state.offsetBeat;let audible=state.audio.currentTime;try{const s=state.audio.getOutputTimestamp?.();if(s&&s.performanceTime>0&&s.contextTime>0)audible=s.contextTime+(performance.now()-s.performanceTime)/1000;}catch{}return Math.max(0,state.offsetBeat+(audible-state.startAt-state.settings.offset/1000)/SPB);}
function pauseRun(interrupted){keys.clear();if(interrupted)state.interrupted=true;if(!["playing","countdown"].includes(state.screen)||!state.run)return;if(state.screen==="playing")state.offsetBeat=Math.max(state.offsetBeat,state.offsetBeat+(state.audio.currentTime-state.startAt)/SPB);stopSource();state.counting=false;state.pointerId=null;state.interrupted=Boolean(interrupted);showScreen("pause-screen");if(interrupted)toastMessage("Трек остановлен. Нажми «Продолжить», когда будешь готов.");}
function resumeRun(){if(state.screen!=="pause"||!state.run||state.run.ended||state.resuming)return;state.resuming=true;state.interrupted=false;state.audio.resume().then(()=>{if(state.screen==="pause"&&!document.hidden&&!state.interrupted)startCountIn(state.offsetBeat);}).finally(()=>{state.resuming=false;}).catch(()=>toastMessage("Нажми ещё раз, чтобы продолжить звук."));}
function leaveToMenu(){keys.clear();stopSource();state.counting=false;state.run=null;state.pointerId=null;try{tg?.BackButton?.hide?.();}catch{}showScreen("menu-screen");updateBestUI();}
function updateBestUI(){const n=state.best[state.difficulty]||0;$("menu-best").textContent=n?n.toLocaleString("ru-RU"):"—";}
function finishRun(completed){if(!state.run||["result","menu"].includes(state.screen))return;stopSource();state.counting=false;const r=state.run;r.finished=completed;r.ended=!completed;const score=Math.floor(r.score),old=state.best[r.difficulty]||0,isBest=score>old;if(isBest){state.best[r.difficulty]=score;persist();}$("result-kicker").textContent=completed?"ТРЕК ПРОЙДЕН":"СИГНАЛ ЗАТИХ";$("result-title").textContent="МАКАР + ЖЕНЯ";$("final-score").textContent=score.toLocaleString("ru-RU");$("accuracy").textContent=accuracy(r,state.chart)+"%";$("max-combo").textContent=r.maxCombo;$("distance").textContent=Math.round(Math.min(1,r.beat/state.chart.durationBeats)*100)+"%";$("best-badge").textContent=isBest?"НОВЫЙ РЕКОРД ✦":(old?"РЕКОРД "+old.toLocaleString("ru-RU"):"");showScreen("result-screen");try{tg?.HapticFeedback?.notificationOccurred?.(completed?"success":"warning");}catch{}}
async function shareResult(){const r=state.run,text=["МАКАР + ЖЕНЯ · NEON RUSH 140 BPM",r.difficulty.toUpperCase()+" · "+Math.floor(r.score).toLocaleString("ru-RU")+" очков · точность "+accuracy(r,state.chart)+"% · комбо "+r.maxCombo].join("\n");try{if(navigator.share){await navigator.share({title:"МАКАР + ЖЕНЯ",text});return;}if(!navigator.clipboard?.writeText)throw new Error("Clipboard unavailable");await navigator.clipboard.writeText(text);toastMessage("РЕЗУЛЬТАТ СКОПИРОВАН");}catch(error){if(error.name!=="AbortError")toastMessage("НЕ УДАЛОСЬ ПОДЕЛИТЬСЯ");}}
const actions={"play-button":begin,"pause-button":()=>pauseRun(false),"resume-button":resumeRun,"restart-button":begin,"again-button":begin,"quit-button":leaveToMenu,"result-menu-button":leaveToMenu,"how-button":()=>showScreen("help-screen"),"help-close":()=>showScreen("menu-screen"),"settings-button":()=>{applySettings();showScreen("settings-screen");},"settings-close":()=>{persist();showScreen("menu-screen");},"share-button":shareResult};
for(const [id,fn]of Object.entries(actions))$(id).addEventListener("click",fn);
document.querySelectorAll(".difficulty").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".difficulty").forEach(x=>x.classList.toggle("selected",x===b));state.difficulty=b.dataset.difficulty;updateBestUI();}));
$("music-volume").addEventListener("input",e=>{state.settings.music=Number(e.target.value);applySettings();persist();});
$("sfx-volume").addEventListener("input",e=>{state.settings.sfx=Number(e.target.value);if(state.sfxGain)state.sfxGain.gain.setTargetAtTime(state.settings.sfx,state.audio.currentTime,.03);persist();});
$("offset").addEventListener("input",e=>{state.settings.offset=Number(e.target.value);$("offset-value").value=state.settings.offset+" мс";persist();});
$("reduced-motion").addEventListener("change",e=>{state.settings.reduced=e.target.checked;applySettings();persist();});
applySettings();updateBestUI();
canvas.addEventListener("pointerdown",e=>{if(state.screen!=="playing"||state.pointerId!==null)return;state.pointerId=e.pointerId;state.pointerX=e.clientX;try{canvas.setPointerCapture(e.pointerId);}catch{}});
canvas.addEventListener("pointermove",e=>{if(state.screen!=="playing"||state.pointerId!==e.pointerId||!state.run)return;const dx=(e.clientX-state.pointerX)/state.scale;state.pointerX=e.clientX;setTarget(state.run,dx);});
function releasePointer(e){if(state.pointerId===e.pointerId)state.pointerId=null;}
canvas.addEventListener("pointerup",releasePointer);canvas.addEventListener("pointercancel",releasePointer);canvas.addEventListener("lostpointercapture",releasePointer);
const keys=new Set();
addEventListener("keydown",e=>{if(["ArrowLeft","ArrowRight","a","d","A","D"," ","Escape"].includes(e.key))e.preventDefault();if(e.key==="Escape"||e.key===" "){if(state.screen==="playing")pauseRun(false);else if(state.screen==="pause")resumeRun();return;}keys.add(e.key.toLowerCase());});
addEventListener("keyup",e=>keys.delete(e.key.toLowerCase()));
addEventListener("visibilitychange",()=>{if(document.hidden)pauseRun(true);});
tg?.onEvent?.("deactivated",()=>pauseRun(true));tg?.onEvent?.("activated",()=>{if(state.screen==="pause")toastMessage("ВОЗВРАТ ИЗ TELEGRAM · НАЖМИ ПРОДОЛЖИТЬ");});
try{tg?.BackButton?.onClick?.(()=>{if(state.screen==="playing")pauseRun(false);else if(state.screen==="pause"||state.screen==="result")leaveToMenu();});}catch{}

function drawBackground(w,h,beat,time){ctx.fillStyle="#070a16";ctx.fillRect(0,0,w,h);const c=w/2,top=-30,bottom=state.playerY+125,ht=w*.06,hb=w*.54;const g=ctx.createLinearGradient(0,top,0,bottom);g.addColorStop(0,"#0b1023");g.addColorStop(.68,"#10162a");g.addColorStop(1,"#080c18");ctx.fillStyle=g;ctx.beginPath();ctx.moveTo(c-ht,top);ctx.lineTo(c+ht,top);ctx.lineTo(c+hb,bottom);ctx.lineTo(c-hb,bottom);ctx.closePath();ctx.fill();for(const side of [-1,1]){ctx.beginPath();ctx.moveTo(c+side*ht,top);ctx.lineTo(c+side*hb,bottom);ctx.strokeStyle=side<0?"#2ceaff55":"#ff3b8150";ctx.lineWidth=1;ctx.stroke();for(let i=1;i<=4;i++){const t=i/5,y=top+(bottom-top)*t,x=c+side*(ht+(hb-ht)*t);ctx.fillStyle=side<0?"#39dbff":"#e84c8b";ctx.globalAlpha=.28+((beat*.25+i)%1)*.15;ctx.fillRect(x-2,y,4,12+t*30);}}ctx.globalAlpha=1;const phase=((beat*state.playerY/4)%42+42)%42;ctx.strokeStyle="#45557522";ctx.lineWidth=1;for(let y=phase;y<h;y+=42){const f=y/h,half=ht+(hb-ht)*f;ctx.beginPath();ctx.moveTo(c-half,top+(bottom-top)*f);ctx.lineTo(c+half,top+(bottom-top)*f);ctx.stroke();}for(let i=-4;i<=4;i++){ctx.beginPath();ctx.moveTo(c+i*ht/4,top);ctx.lineTo(c+i*hb/4,bottom);ctx.stroke();}if(!state.settings.reduced)for(let i=0;i<18;i++){const y=((i*83+time*.055*(i%3+1))%(h+30))-15,side=i%2?-1:1,x=c+side*(ht+(hb-ht)*Math.max(0,y/bottom));ctx.globalAlpha=.2;ctx.fillStyle=i%3?"#48eaff":"#ff3d83";ctx.fillRect(x,y,1.5,1.5);}ctx.globalAlpha=1;}
function drawWall(e,beat){const py=state.playerY,speed=py/e.approachBeats,y=py+(e.beat-beat)*speed,half=e.height/2,l=(e.gapCenter-e.gapWidth/2)*360,r=(e.gapCenter+e.gapWidth/2)*360;const grad=ctx.createLinearGradient(0,y-half,0,y+half);grad.addColorStop(0,"#a91e56");grad.addColorStop(.5,"#ff3d83");grad.addColorStop(1,"#851b4c");ctx.save();ctx.shadowColor="#ff287c";ctx.shadowBlur=state.settings.reduced?4:12;for(const [x,w]of [[0,l],[r,360-r]])if(w>0){ctx.fillStyle=grad;ctx.fillRect(x,y-half,w,e.height);ctx.fillStyle="#ffd3e2";ctx.globalAlpha=.5;ctx.fillRect(x,y-half,w,2);ctx.globalAlpha=.2;for(let xx=x+8;xx<x+w;xx+=13)ctx.fillRect(xx,y-half+4,2,e.height-8);ctx.globalAlpha=1;}ctx.restore();ctx.fillStyle="#ff9bbd";ctx.fillRect(l-2,y-half,3,4);ctx.fillRect(r-1,y-half,3,4);}
function drawGate(e,beat){const x=e.x*360,y=state.playerY+(e.beat-beat)*state.playerY/4;if(y< -42||y>state.worldHeight+35)return;const result=state.run?.gateResults.get(e.id),color=e.risk?"#ffcf67":"#4cecff",size=12+Math.max(0,4-Math.abs(e.beat-beat))*1.6;ctx.save();ctx.translate(x,y);ctx.rotate(Math.PI/4);ctx.strokeStyle=result==="perfect"?"#e6ffff":result==="good"?"#b6fff7":result==="miss"?"#7c3656":color;ctx.lineWidth=2;ctx.shadowColor=color;ctx.shadowBlur=state.settings.reduced?2:10;ctx.strokeRect(-size/2,-size/2,size,size);ctx.restore();ctx.strokeStyle=color;ctx.globalAlpha=.4;ctx.beginPath();ctx.moveTo(x,y-size);ctx.lineTo(x,y+size);ctx.stroke();ctx.globalAlpha=1;ctx.fillStyle=color;ctx.font="bold 12px Oxanium,monospace";ctx.textAlign="center";ctx.fillText(e.direction<0?"←":"→",x,y+4);if(e.risk){ctx.beginPath();ctx.arc(x,y,size+5,0,Math.PI*2);ctx.strokeStyle="#ffcf6777";ctx.setLineDash([2,3]);ctx.stroke();ctx.setLineDash([]);}}
function drawLaser(l,beat){const wy=state.playerY+(l.warnBeat-beat)*state.playerY/4,ay=state.playerY+(l.startBeat-beat)*state.playerY/4,x=l.x*360;if(wy>0&&wy<state.worldHeight){ctx.save();ctx.globalAlpha=.45;ctx.strokeStyle="#ff486f";ctx.setLineDash([4,5]);ctx.beginPath();ctx.moveTo(x,wy-16);ctx.lineTo(x,wy+16);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle="#ff7897";ctx.textAlign="center";ctx.fillText("!",x,wy-19);ctx.restore();}if(beat>=l.startBeat&&beat<l.endBeat){ctx.save();ctx.shadowColor="#ff295b";ctx.shadowBlur=state.settings.reduced?2:10;ctx.fillStyle="#ff305f";ctx.globalAlpha=.8;ctx.fillRect(x-l.width/2,ay-9,l.width,18);ctx.restore();}}
function drawPickups(p,beat,time){const y=state.playerY+(p.beat-beat)*state.playerY/4;if(y<0||y>state.worldHeight)return;ctx.save();ctx.translate(p.x*360,y);ctx.rotate(Math.PI/4);ctx.strokeStyle="#fff";ctx.lineWidth=2;ctx.shadowColor="#fff";ctx.shadowBlur=state.settings.reduced?2:12;ctx.strokeRect(-8,-8,16,16);ctx.fillStyle="#7deaff";ctx.fillRect(-3,-3,6,6);ctx.restore();}
function drawShip(r,time){ctx.save();ctx.translate(r.x,state.playerY);if(r.beat<r.invulnerableUntil){ctx.strokeStyle="#4cecff99";ctx.beginPath();ctx.arc(0,0,19,0,Math.PI*2);ctx.stroke();}if(r.shield){ctx.strokeStyle="#ffffffa8";ctx.setLineDash([3,3]);ctx.beginPath();ctx.arc(0,0,24,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);}if(r.beat<r.flowUntil){ctx.strokeStyle="#ffe5a8";ctx.globalAlpha=.42;ctx.beginPath();ctx.moveTo(0,20);ctx.lineTo(0,54+(state.settings.reduced?0:8*Math.sin(time*.012)));ctx.stroke();ctx.globalAlpha=1;}ctx.shadowColor=r.beat<r.flowUntil?"#ffcb6b":"#3ee8ff";ctx.shadowBlur=state.settings.reduced?2:14;ctx.fillStyle="#3feaff";ctx.beginPath();ctx.moveTo(0,-19);ctx.lineTo(-15,13);ctx.lineTo(-7,11);ctx.lineTo(0,16);ctx.lineTo(7,11);ctx.lineTo(15,13);ctx.closePath();ctx.fill();ctx.shadowBlur=0;ctx.fillStyle="#d8fdff";ctx.beginPath();ctx.moveTo(0,-12);ctx.lineTo(-4,7);ctx.lineTo(0,5);ctx.lineTo(4,7);ctx.closePath();ctx.fill();const thrust=state.settings.reduced?10:11+6*Math.abs(Math.sin(r.beat*Math.PI*2));ctx.fillStyle=r.beat<r.flowUntil?"#ffe296":"#ff66ad";ctx.beginPath();ctx.moveTo(-5,12);ctx.lineTo(0,thrust+9);ctx.lineTo(5,12);ctx.closePath();ctx.fill();ctx.restore();}
function render(time){const sx=canvas.width/state.width,sy=canvas.height/state.height;ctx.setTransform(sx,0,0,sy,0,0);ctx.fillStyle="#070a16";ctx.fillRect(0,0,state.width,state.height);ctx.setTransform(sx*state.scale,0,0,sy*state.scale,sx*(state.width-360*state.scale)/2,0);const beat=state.run?.beat||0;drawBackground(360,state.worldHeight,beat,time);if(!state.run)return;for(const e of state.run.events){if(e.type==="wall")drawWall(e,beat);else if(e.type==="crossGate")drawGate(e,beat);}for(const l of makeLasers(state.chart,state.run.hard))drawLaser(l,beat);for(const p of makePickups(state.chart))if(!state.run.processed.has(p.id))drawPickups(p,beat,time);if(!state.settings.reduced)for(const p of state.run.particles){ctx.globalAlpha=Math.max(0,1-p.age/p.life);ctx.fillStyle=p.color;ctx.shadowColor=p.color;ctx.shadowBlur=5;ctx.fillRect(p.x-p.size/2,p.y-p.size/2,p.size,p.size);}ctx.globalAlpha=1;ctx.shadowBlur=0;const shock=state.run.effects.find(e=>e.type==="shock");if(shock&&!state.settings.reduced){const f=shock.age/shock.life;ctx.strokeStyle="#ff6b9b";ctx.globalAlpha=1-f;ctx.lineWidth=2;ctx.beginPath();ctx.arc(state.run.x,state.playerY,12+f*75,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1;}const charge=Math.min(1,state.run.charge/8);ctx.strokeStyle=state.run.beat<state.run.flowUntil?"#ffcf67":"#4cecff88";ctx.lineWidth=2;ctx.beginPath();ctx.arc(state.run.x,state.playerY+26,15,-Math.PI/2,-Math.PI/2+Math.PI*2*charge);ctx.stroke();drawShip(state.run,time);if(state.counting){const n=Math.max(1,Math.ceil((state.startAt-state.audio.currentTime)/SPB));ctx.fillStyle="#dffaff";ctx.font="700 52px Oxanium";ctx.textAlign="center";ctx.shadowColor="#4cecff";ctx.shadowBlur=16;ctx.fillText(String(n),180,state.worldHeight*.36);ctx.shadowBlur=0;}}
function updateHUD(){const r=state.run;if(!r)return;$("score").textContent=Math.floor(r.score).toString().padStart(6,"0");$("combo").textContent="×"+(1+Math.min(3,Math.floor(r.combo/8))+(r.beat<r.flowUntil?1:0));$("lives").textContent="◆ ".repeat(Math.max(0,r.lives))+(r.shield?" ◇":"");$("section").textContent=activeSection(state.chart,r.beat).replaceAll("_"," ").toUpperCase()+" · 140 BPM";$("track-progress").style.width=(100*Math.min(1,r.beat/state.chart.durationBeats))+"%";}

function frame(time){if(state.screen==="countdown"&&state.audio.currentTime>=state.startAt){state.counting=false;showScreen("none");state.lastFrame=time;}if(state.screen==="playing"&&state.run&&!state.counting){if(time-state.lastFrame>300){pauseRun(true);}else{state.accumulator+=Math.max(0,(time-state.lastFrame)/1000);state.lastFrame=time;let steps=0;while(state.accumulator>=FIXED_STEP&&steps<20){const next=state.run.beat+FIXED_STEP/SPB;if(next>audibleBeat())break;if(keys.has("arrowleft")||keys.has("a"))setTarget(state.run,-MAX_SPEED*FIXED_STEP);if(keys.has("arrowright")||keys.has("d"))setTarget(state.run,MAX_SPEED*FIXED_STEP);advanceRun(state.run,state.chart,next,FIXED_STEP);playSfx(state.run.lastSfx);state.accumulator-=FIXED_STEP;steps++;}updateHUD();if(state.run.ended)finishRun(false);else if(state.run.finished)finishRun(true);}}else if(state.screen==="countdown"){const remain=Math.max(0,(state.startAt-state.audio.currentTime)/SPB);$("loading-message").textContent=remain<.45?"ПРИГОТОВЬСЯ":Math.ceil(remain)+" · МАКАР + ЖЕНЯ";}render(time);requestAnimationFrame(frame);}
requestAnimationFrame(frame);
window.addEventListener("load",()=>{try{tg?.BackButton?.hide?.();}catch{}});
window.__MAKAR_GAME__={get state(){return state;},get engine(){return {SPB,FIXED_STEP,createRun,advanceRun,validateChart,accuracy};},start:begin,pause:()=>pauseRun(false),resume:resumeRun};
